name: Generate Swagger Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'  # Adjust based on your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run the API in the background
        run: |
          dotnet run --no-build --configuration Release > output.log 2>&1 &
          sleep 10  # Wait for the server to start

      - name: Find the running port
        run: |
          PORT=$(grep -oP 'http://localhost:\K\d+' output.log | head -1)
          echo "API is running on port $PORT"
          echo "PORT=$PORT" >> $GITHUB_ENV

      - name: Fetch Swagger JSON
        run: curl http://localhost:${{ env.PORT }}/swagger/v1/swagger.json -o swagger.json

      - name: Move Swagger JSON to docs folder
        run: |
          mkdir -p docs
          mv swagger.json docs/swagger.json

      - name: Commit and push Swagger JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/swagger.json
          git commit -m "Update Swagger API documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
